// skill_pdf.js - Fixed & Integrated
// Author: NI MBAYA
// Username: GuruTech
// Botname: XGURU
// Repository: https://github.com/ADDICT-HUB/XGURU

const { evt } = require("../gift");
const fs = require("fs-extra");
const path = require("path");
const config = require("../config");

let PDFDocument;
try {
    PDFDocument = require("pdfkit");
    console.log("✅ PDFKit module loaded - NI MBAYA 😅");
} catch (error) {
    console.log("⚠️ PDFKit not available, using fallback mode");
    PDFDocument = null;
}

// --- UTILITY: PDF GENERATOR ---
function createSimplePDF(text, filename) {
    return new Promise((resolve, reject) => {
        try {
            if (!PDFDocument) {
                const fallbackContent = `𝐗-𝐆𝐔𝐑𝐔 𝐏𝐃𝐅 𝐃𝐎𝐂𝐔𝐌𝐄𝐍𝐓\n\nGenerated by XGURU Bot\nAuthor: NI MBAYA\nContent:\n${text}`;
                fs.writeFileSync(filename, fallbackContent);
                return resolve(filename);
            }
            
            const doc = new PDFDocument();
            const stream = fs.createWriteStream(filename);
            doc.pipe(stream);
            
            // Branding Header
            doc.fontSize(22).text('𝐗-𝐆𝐔𝐑𝐔 𝐌𝐃 𝐏𝐃𝐅', { align: 'center' }).moveDown();
            doc.fontSize(10).text('Generated by: NI MBAYA', { align: 'center' });
            doc.text('Repo: https://github.com/ADDICT-HUB/XGURU', { align: 'center' }).moveDown(2);
            
            // Content
            doc.fontSize(12).text(text, { align: 'left' });
            doc.end();
            
            stream.on('finish', () => resolve(filename));
            stream.on('error', reject);
        } catch (error) { reject(error); }
    });
}

// --- COMMAND: TO PDF ---
evt({
    pattern: "topdf",
    desc: "Convert text to professional PDF",
    category: "tools"
}, async (from, Gifted, { args, q, reply }) => {
    try {
        if (!q) return reply(`*NI MBAYA!* ⚠️ Please provide text.\nExample: ${config.PREFIX}topdf Hello GuruTech`);

        await reply("⏳ *Processing PDF... Please wait.*");
        
        const filename = `xguru-${Date.now()}.pdf`;
        const filepath = path.join(__dirname, "..", "temp", filename);
        await fs.ensureDir(path.dirname(filepath));

        await createSimplePDF(q, filepath);

        await Gifted.sendMessage(from, {
            document: fs.readFileSync(filepath),
            mimetype: "application/pdf",
            fileName: `XGURU_DOC_${Date.now()}.pdf`,
            caption: `📄 *𝐏𝐃𝐅 𝐆𝐄𝐍𝐄𝐑𝐀𝐓𝐄𝐃 𝐒𝐔𝐂𝐂𝐄𝐒𝐒𝐅𝐔𝐋𝐋𝐘*\n\n⋄ *Author:* NI MBAYA\n⋄ *Source:* XGURU MD\n\n> *NI MBAYA 😅*`
        });

        // Cleanup temp file
        setTimeout(() => fs.unlink(filepath).catch(() => {}), 10000);
        
    } catch (error) {
        console.error("PDF Error:", error);
        reply("❌ *Error generating PDF.* Ensure `pdfkit` is installed.");
    }
});

// --- COMMAND: TEXT FILE ---
evt({
    pattern: "textfile",
    desc: "Convert text to .txt file",
    category: "tools"
}, async (from, Gifted, { q, reply }) => {
    try {
        if (!q) return reply("⚠️ Please provide text for the file.");

        const filename = `xguru-${Date.now()}.txt`;
        const filepath = path.join(__dirname, "..", "temp", filename);
        await fs.ensureDir(path.dirname(filepath));

        const content = `𝐗-𝐆𝐔𝐑𝐔 𝐌𝐃 𝐓𝐄𝐗𝐓 𝐅𝐈𝐋𝐄\n\nAuthor: NI MBAYA\n\nContent:\n${q}`;
        fs.writeFileSync(filepath, content);

        await Gifted.sendMessage(from, {
            document: fs.readFileSync(filepath),
            mimetype: "text/plain",
            fileName: `XGURU_TEXT_${Date.now()}.txt`,
            caption: `📝 *𝐓𝐄𝐗𝐓 𝐅𝐈𝐋𝐄 𝐂𝐑𝐄𝐀𝐓𝐄𝐃*\n\n⋄ *Author:* NI MBAYA\n\n> *NI MBAYA 😅*`
        });

        setTimeout(() => fs.unlink(filepath).catch(() => {}), 10000);
    } catch (e) { reply("❌ Failed to create text file."); }
});

// --- COMMAND: DOC HELP ---
evt({
    pattern: "doc",
    desc: "Help for document tools",
    category: "tools"
}, async (from, Gifted, { reply }) => {
    const help = `
📄 *𝐗-𝐆𝐔𝐑𝐔 𝐃𝐎𝐂𝐔𝐌𝐄𝐍𝐓 𝐓𝐎𝐎𝐋𝐒*

╔════════════════════════╗
  ⋄ ${config.PREFIX}topdf (text)
  ⋄ ${config.PREFIX}textfile (text)
╚════════════════════════╝

*System Status:*
⋄ PDFKit: ${PDFDocument ? '✅ Ready' : '❌ Missing'}
⋄ Author: NI MBAYA

> *NI MBAYA 😅*`;
    return reply(help);
});

module.exports = { createSimplePDF };
console.log("✅ PDF Tools plugin fully integrated - NI MBAYA 😅");
